'use strict';

// tests for getArtisTours
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getArtisTours', '/handler.js', 'getArtisTours');

describe('getArtisTours', () => {
  before((done) => {
    done();
  });

  it('implement tests here', async () => {
    const response = await wrapped.run({pathParameters: {name: "The Killers"}});
    expect(response.statusCode).to.be.equal(200);
  });
});
